version: "3.9"
services:
  fastapi-backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/chatbot_db

  next-frontend:
    build: ./frontend
    depends_on:
      - fastapi-backend
      - postgres-db
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: supersecretjwtkey
      NEXTAUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:password@postgres-db:5432/chatbot_db

  postgres-db:
    image: postgres:17
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
